from .cotere import COTERE
from .my_baseline import MY_BASELINE
from .my_baseline_sdefeat import MY_BASELINE_SDEFEAT
from .my_baseline_sdelight import MY_BASELINE_SDELIGHT
from .my_baseline_sdelight_prob import MY_BASELINE_SDELIGHT_PROB
from .my_baseline_rbfkan_prob import MY_BASELINE_RBFKAN_PROB
from .prob import PROB
from .probkan  import PROBKAN
from .probkan_v2 import PROBKAN_V2
from .kanattn import KANATTN
from .my_baseline_kanattn_rbf import MY_BASELINE_KANATTN_RBF
from .my_baseline_kanattn_rbf_v2 import MY_BASELINE_KANATTN_RBF_V2
from .my_baseline_kanhead_rbf import MY_BASELINE_KANHEAD_RBF
from .my_baseline_kanhead_spline import MY_BASELINE_KANHEAD_SPLINE
from .my_baseline_kanhead_rbf_residual import MY_BASELINE_KANHEAD_RBF_RESIDUAL
from .my_baseline_kandecoder_gate_rbf import MY_BASELINE_KANDECODER_GATE_RBF
from .my_baseline_kanskip_fusion_rbf import MY_BASELINE_KANSKIP_FUSION_RBF
from .my_baseline_kanhead_spline_residual import MY_BASELINE_KANHEAD_SPLINE_RESIDUAL
from .my_baseline_sdelight_kanhead_rbf_residual import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS

from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_regab import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_REGAB
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_sdeenergy_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDEENERGY_BINS

from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_v2 import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_V2
from .my_baseline_strongenc import MY_BASELINE_STRONGENC
from .my_baseline_strongenc_kanhead_rbf_residual import MY_BASELINE_STRONGENC_KANHEAD_RBF_RESIDUAL
from .my_baseline_strongenc_sdelight_kanhead_rbf_residual_sdeloss import MY_BASELINE_STRONGENC_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS

from .my_baseline_sdelight_kanhead_rbf_residual_perstep_sdeloss_bins_v2 import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_PERSTEP_SDELOSS_BINS_V2
from .my_baseline_sdelight_kanhead_rbf_residual_perstep_smooth import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_PERSTEP_SMOOTH
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_mixed import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_MIXED

from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_mixed03 import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_MIXED03
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_horizon import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HORIZON
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_smooth import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_SMOOTH
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_huber import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HUBER

from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_huber_light import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HUBER_LIGHT
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_topk import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_TOPK
from .my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_edge import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_EDGE

from .my_baseline_sdelight_kanhead_rbf_residual_multikan_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_MULTIKAN_SDELOSS_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_gatedkan_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_GATEDKAN_SDELOSS_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_tempmix_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_TEMPMIX_SDELOSS_BINS

from .my_baseline_sdelight_kanhead_rbf_residual_stemplus_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_STEMPLUS_SDELOSS_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_dilated_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_DILATED_SDELOSS_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_skipgate_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SKIPGATE_SDELOSS_BINS

from .my_baseline_uv import MY_BASELINE_UV
from .my_baseline_kanhead_rbf_residual_uv import MY_BASELINE_KANHEAD_RBF_RESIDUAL_UV
from .my_baseline_kanhead_spline_residual_uv import MY_BASELINE_KANHEAD_SPLINE_RESIDUAL_UV

from .my_baseline_sdelight_kanhead_rbf_residual_sdeenergy_nll_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDEENERGY_NLL_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_uv_sdeenergy_nll_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_UV_SDEENERGY_NLL_BINS
from .my_baseline_sdelight_kanhead_rbf_residual_uv_sdeloss_bins import MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_UV_SDELOSS_BINS

method_maps = {
    'cotere': COTERE,
    'my_baseline': MY_BASELINE,
    'my_baseline_sdefeat': MY_BASELINE_SDEFEAT,
    'my_baseline_sdelight': MY_BASELINE_SDELIGHT,
    'my_baseline_sdelight_prob': MY_BASELINE_SDELIGHT_PROB,
    'my_baseline_rbfkan_prob': MY_BASELINE_RBFKAN_PROB,
    'prob': PROB,
    'probkan': PROBKAN,
    'probkan_v2': PROBKAN_V2,
    'kanattn': KANATTN,
    'my_baseline_kanattn_rbf': MY_BASELINE_KANATTN_RBF,
    'my_baseline_kanattn_rbf_v2': MY_BASELINE_KANATTN_RBF_V2,
    'my_baseline_kanhead_rbf': MY_BASELINE_KANHEAD_RBF,
    'my_baseline_kanhead_spline': MY_BASELINE_KANHEAD_SPLINE,
    'my_baseline_kanhead_rbf_residual': MY_BASELINE_KANHEAD_RBF_RESIDUAL,
    'my_baseline_kandecoder_gate_rbf': MY_BASELINE_KANDECODER_GATE_RBF,
    'my_baseline_kanskip_fusion_rbf': MY_BASELINE_KANSKIP_FUSION_RBF,
    'my_baseline_kanhead_spline_residual': MY_BASELINE_KANHEAD_SPLINE_RESIDUAL,
    'my_baseline_sdelight_kanhead_rbf_residual': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_regab': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_REGAB,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeenergy_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDEENERGY_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_v2': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_V2,
    'my_baseline_strongenc': MY_BASELINE_STRONGENC,
    'my_baseline_strongenc_kanhead_rbf_residual': MY_BASELINE_STRONGENC_KANHEAD_RBF_RESIDUAL,
    'my_baseline_strongenc_sdelight_kanhead_rbf_residual_sdeloss': MY_BASELINE_STRONGENC_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS,
    'my_baseline_sdelight_kanhead_rbf_residual_perstep_sdeloss_bins_v2': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_PERSTEP_SDELOSS_BINS_V2,
    'my_baseline_sdelight_kanhead_rbf_residual_perstep_smooth': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_PERSTEP_SMOOTH,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_mixed': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_MIXED,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_mixed03': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_MIXED03,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_horizon': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HORIZON,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_huber': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HUBER,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_smooth': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_SMOOTH,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_huber_light': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HUBER_LIGHT,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_topk': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_TOPK,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeloss_bins_edge': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_EDGE,
    'my_baseline_sdelight_kanhead_rbf_residual_multikan_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_MULTIKAN_SDELOSS_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_gatedkan_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_GATEDKAN_SDELOSS_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_tempmix_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_TEMPMIX_SDELOSS_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_stemplus_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_STEMPLUS_SDELOSS_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_dilated_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_DILATED_SDELOSS_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_skipgate_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SKIPGATE_SDELOSS_BINS,
    'my_baseline_uv': MY_BASELINE_UV,
    'my_baseline_kanhead_rbf_residual_uv': MY_BASELINE_KANHEAD_RBF_RESIDUAL_UV,
    'my_baseline_kanhead_spline_residual_uv': MY_BASELINE_KANHEAD_SPLINE_RESIDUAL_UV,
    'my_baseline_sdelight_kanhead_rbf_residual_sdeenergy_nll_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDEENERGY_NLL_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_uv_sdeenergy_nll_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_UV_SDEENERGY_NLL_BINS,
    'my_baseline_sdelight_kanhead_rbf_residual_uv_sdeloss_bins': MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_UV_SDELOSS_BINS,
}

__all__ = [
    'COTERE',
    'MY_BASELINE',
    'MY_BASELINE_SDEFEAT',
    'MY_BASELINE_SDELIGHT',
    'MY_BASELINE_SDELIGHT_PROB',
    'MY_BASELINE_RBFKAN_PROB',
    'PROB',
    'PROBKAN',
    'PROBKAN_V2',
    'KANATTN',
    'MY_BASELINE_KANATTN_RBF',
    'MY_BASELINE_KANATTN_RBF_V2',
    'MY_BASELINE_KANHEAD_RBF',
    'MY_BASELINE_KANHEAD_SPLINE',
    'MY_BASELINE_KANHEAD_RBF_RESIDUAL',
    'MY_BASELINE_KANDECODER_GATE_RBF',
    'MY_BASELINE_KANSKIP_FUSION_RBF',
    'MY_BASELINE_KANHEAD_SPLINE_RESIDUAL',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_REGAB',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDEENERGY_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_V2',
    'MY_BASELINE_STRONGENC',
    'MY_BASELINE_STRONGENC_KANHEAD_RBF_RESIDUAL',
    'MY_BASELINE_STRONGENC_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_PERSTEP_SDELOSS_BINS_V2',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_PERSTEP_SMOOTH',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_MIXED',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_MIXED03',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HORIZON',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_SMOOTH',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HUBER',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_HUBER_LIGHT',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_TOPK',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDELOSS_BINS_EDGE',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_MULTIKAN_SDELOSS_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_GATEDKAN_SDELOSS_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_TEMPMIX_SDELOSS_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_STEMPLUS_SDELOSS_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_DILATED_SDELOSS_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SKIPGATE_SDELOSS_BINS',
    'MY_BASELINE_UV',
    'MY_BASELINE_KANHEAD_RBF_RESIDUAL_UV',
    'MY_BASELINE_KANHEAD_SPLINE_RESIDUAL_UV',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_SDEENERGY_NLL_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_UV_SDEENERGY_NLL_BINS',
    'MY_BASELINE_SDELIGHT_KANHEAD_RBF_RESIDUAL_UV_SDELOSS_BINS',
]



